# Generated by Django 5.1.1 on 2024-09-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vat_payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatumAktualizacieZoznamu', models.DateField()),
                ('IC_DPH', models.CharField(max_length=20)),
                ('ICO', models.CharField(max_length=20)),
                ('NAZOV_DS', models.CharField(max_length=200)),
                ('OBEC', models.CharField(max_length=100)),
                ('PSC', models.CharField(max_length=10)),
                ('ULICA_CISLO', models.CharField(max_length=100)),
                ('STAT', models.CharField(max_length=20)),
                ('DRUH_REG_DPH', models.CharField(max_length=5)),
                ('DATUM_REG', models.DateField()),
                ('DATUM_ZMENY_DRUHU_REG', models.DateField()),
            ],
        ),
    ]
