# Generated by Django 5.1.1 on 2024-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat_payer',
            name='DATUM_ZMENY_DRUHU_REG',
            field=models.DateField(blank=True, null=True),
        ),
    ]
