# Generated by Django 5.1.1 on 2024-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_vat_type_undefined_item_itemtranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='itemtranslation',
            constraint=models.UniqueConstraint(fields=('item', 'language_code'), name='unique_item_language_code'),
        ),
    ]
