# Generated by Django 5.1.1 on 2024-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_vat_payer_datum_zmeny_druhu_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat_payer',
            name='DATUM_REG',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='DRUH_REG_DPH',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='ICO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='IC_DPH',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='NAZOV_DS',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='OBEC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='PSC',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='STAT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vat_payer',
            name='ULICA_CISLO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
