# Generated by Django 5.1.1 on 2024-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_vat_payer_datum_reg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat_payer',
            name='STAT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
