# Generated by Django 5.1.1 on 2024-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_vat_payer_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat_payer_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRUH_REG_DPH', models.CharField(max_length=5)),
                ('PLATNY_DRUH_REG', models.BooleanField()),
            ],
        ),
    ]
