# Generated by Django 5.1.1 on 2024-10-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_customer_nazov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DIC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ICO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='IC_DPH',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
